# Generated by Django 4.0.3 on 2022-03-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status_addess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addess',
            new_name='Address',
        ),
    ]
